services:
  dex:
    image: ghcr.io/dexidp/dex:latest
    volumes:
      - ./dex.yaml:/etc/dex/config.docker.yaml
      - dex_data:/var/dex
    env_file: dex.env
    expose:
      - 5556
    restart: unless-stopped

  proxy:
    image: ghcr.io/kotx/dex-tailscale:latest
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    restart: unless-stopped

volumes:
  dex_data:
